version: "3.8"

services:
    streamer:
        build: ./streamer
        ports:
            - "5000:5000"
        volumes:
            - ./streamer:/app

    # client:
    #     build: ./client
    #     ports:
    #         - "3000:3000"
    #     volumes:
    #         - ./client/node_modules:/app/node_modules

    core:
        build: ./core
        ports:
            - "4000:4000"
        volumes:
            - ./core:/app
        command: ["npm", "run", "dev"]

    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./db/data:/data/postgres

    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080