version: '3.8'

services:
    streamer:
        build: ./streamer
        restart: always
        ports:
            - '5000:5000'
        volumes:
            - ./streamer/.venv:/app/.venv

    # client:
    #     build: ./client
    #     ports:
    #         - "3000:3000"
    #     volumes:
    #         - ./client/node_modules:/app/node_modules

    core:
        build: ./core
        restart: always
        depends_on:
            - db
            - minio
            - streamer
        ports:
            - '4000:4000'
        volumes:
            - ./core/node_modules:/app/node_modules
        # command: sleep infinity
        command: npm run start
        env_file:
            - ./core/.env

    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - '5432:5432'
        volumes:
            - dbData:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    prisma-studio:
        depends_on:
            - db
        build: 
            context: ./core
            dockerfile: prisma.Dockerfile
        ports:
            - "5555:5555"

    minio:
        image: minio/minio
        environment:
            - MINIO_ROOT_USER=user
            - MINIO_ROOT_PASSWORD=password
            - MINIO_ACCESS_KEY=userAccess
            - MINIO_SECRET_KEY=userPassword
        volumes:
            - minioData:/data
        command: server data/minio --console-address :9090
        ports:
            - 9000:9000
            - 9090:9090
        healthcheck:
            test:
                ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
            interval: 30s
            timeout: 20s
            retries: 3

volumes:
    dbData:
    minioData: